# -*- coding: utf-8 -*-
"""
ONE PROCESS block icon generator (P4, v1.1.3).

Owner's verdict on the v1.0 pack: the icons were near-identical rounded boxes
that did not say what the block does — RO, NF, UF and MD were indistinguishable.
This generator replaces them with a designed SYSTEM:

  1. DISTINCT SILHOUETTE per process class (capsule vessel / packed column /
     electrode stack / staged train / pond / rotor), so the eye separates blocks
     before reading anything.
  2. A FUNCTIONAL detail that states the physics (what is blocked vs. what
     passes, bubbles, crystals, effects, rays...).
  3. The BLOCK CODE baked into the art. Aspen gives a CAPE-OPEN block no name on
     the flowsheet body, so the icon is the only place identity can live there
     (see P2); it also makes the palette self-explanatory in both simulators.
  4. A FAMILY ACCENT colour (blue / amber / violet / teal / red) over the ONE
     PROCESS navy outline, so families group at a glance.

Everything must ALSO read as monochrome line art: Aspen flowsheet icons are
drawn from the outlines only (see svg_to_aspen_icon.py), so no meaning may
depend on colour or fill alone.

Output: icons/OP-*.svg  (source of truth; Aspen + DWSIM pipelines both read it)
Then:   python icons/render_png.py   -> icons/png/OP-*.png (DWSIM + packaging)

SVG is restricted to <rect>, <circle>, <path> and <text> — the only elements the
Aspen icon converter understands.
"""
import os

OUT = os.path.dirname(os.path.abspath(__file__))

NAVY = "#1B3A5C"
WHITE = "#FFFFFF"

FAMILY = {
    "membrane": ("#29ABE2", "#CFEAF9"),
    "thermal":  ("#F2A03D", "#FCE7CC"),
    "electro":  ("#7C5CD6", "#E3DBF8"),
    "sorption": ("#2FB39B", "#D0EFE9"),
    "energy":   ("#E5564E", "#FBDCDA"),
}

SW = 2.2          # main stroke
SWT = 1.5         # detail stroke
TEXT_Y = 58       # code baseline


# ---------------------------------------------------------------- primitives
def line(x1, y1, x2, y2, w=SW, color=NAVY, dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<path d="M{x1} {y1} L{x2} {y2}" fill="none" stroke="{color}" '
            f'stroke-width="{w}" stroke-linecap="round"{d}/>')


def rect(x, y, w, h, rx=0, fill="none", stroke=NAVY, sw=SW):
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}" stroke-linejoin="round"/>')


def circle(cx, cy, r, fill="none", stroke=NAVY, sw=SW):
    return (f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}" stroke="{stroke}" '
            f'stroke-width="{sw}"/>')


def dot(cx, cy, r=1.7, fill=NAVY):
    return f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}"/>'


def path(d, fill="none", stroke=NAVY, sw=SW, cap="round"):
    return (f'<path d="{d}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}" '
            f'stroke-linejoin="round" stroke-linecap="{cap}"/>')


def stub(x1, y, x2):
    """Horizontal port stub — the visual cue that this is connectable equipment."""
    return line(x1, y, x2, y, SW)


def vstub(x, y1, y2):
    """Vertical port stub (top/bottom nozzles on columns and cone-bottom vessels)."""
    return line(x, y1, x, y2, SW)


def arrow(x1, y1, x2, y2, w=SW, head=3.2, color=NAVY):
    """Straight arrow with a chevron head at (x2,y2)."""
    import math
    a = math.atan2(y2 - y1, x2 - x1)
    parts = [line(x1, y1, x2, y2, w, color)]
    for s in (+1, -1):
        b = a + s * 2.5
        parts.append(line(x2, y2, x2 + head * math.cos(b), y2 + head * math.sin(b), w, color))
    return "".join(parts)


def code_text(label):
    """The block code baked into the art (auto-shrunk to fit)."""
    size = 15 if len(label) <= 3 else (13 if len(label) == 4 else 11)
    return (f'<text x="32" y="{TEXT_Y}" text-anchor="middle" fill="{NAVY}" '
            f'font-family="Segoe UI, Arial, sans-serif" font-size="{size}" '
            f'font-weight="700" letter-spacing="0.4">{label}</text>')


def svg(body, label, comment):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">\n'
            f'  <!-- {comment} Generated by icons/make_icons.py (P4) — do not hand-edit. -->\n'
            f'  {body}\n  {code_text(label)}\n</svg>\n')


# ------------------------------------------------------- shared body shapes
def vessel(fam, x=11, y=8, w=42, h=32, rx=7):
    """Horizontal pressure vessel (membrane blocks)."""
    return rect(x, y, w, h, rx, fill=FAMILY[fam][1])


def column(fam, x=20, y=6, w=24, h=36, rx=6):
    """Vertical packed column (sorption blocks)."""
    return rect(x, y, w, h, rx, fill=FAMILY[fam][1])


def stack(fam, x=13, y=8, w=38, h=32):
    """Electrode / cell stack (electro + energy blocks)."""
    return rect(x, y, w, h, 3, fill=FAMILY[fam][1])


# =========================================================== the 25 blocks
def op_ro():
    acc = FAMILY["membrane"][0]
    b = [stub(2, 24, 11), stub(53, 15, 62), stub(53, 33, 62), vessel("membrane")]
    # thick membrane: nothing gets through but water
    b += [rect(35, 8, 4, 32, 0, fill=acc, sw=SWT)]
    # high-pressure chevrons at the inlet — RO's signature
    b += [path("M14 18 l5 6 -5 6", sw=SW), path("M20 18 l5 6 -5 6", sw=SW)]
    # every salt ion blocked at the membrane face
    b += [dot(30, 15), dot(30, 24), dot(30, 33), dot(33, 19.5), dot(33, 28.5)]
    b += [arrow(41, 24, 50, 24, SWT)]  # clean permeate leaves
    return svg("".join(b), "RO", "OP-RO — Reverse Osmosis: high pressure, total salt rejection.")


def op_nf():
    acc = FAMILY["membrane"][0]
    b = [stub(2, 24, 11), stub(53, 15, 62), stub(53, 33, 62), vessel("membrane")]
    b += [rect(35, 8, 3, 32, 0, fill=acc, sw=SWT)]
    # BIG (multivalent) ions blocked, SMALL (monovalent) ions pass — NF's signature
    b += [dot(28, 16, 2.4), dot(28, 30, 2.4), dot(31, 23, 2.4)]
    b += [dot(43, 19, 1.1), dot(47, 27, 1.1), dot(41, 31, 1.1)]
    b += [arrow(15, 24, 26, 24, SWT)]
    return svg("".join(b), "NF", "OP-NF — Nanofiltration: multivalent ions blocked, monovalent pass.")


def op_uf():
    acc = FAMILY["membrane"][0]
    b = [stub(2, 24, 11), stub(53, 15, 62), stub(53, 33, 62), vessel("membrane")]
    b += [rect(35, 8, 3, 32, 0, fill=acc, sw=SWT)]
    # colloids/macromolecules (irregular blobs) blocked; all dissolved salt passes
    b += [path("M24 14 q4 -3 7 1 q3 4 -1 6 q-5 2 -7 -2 z", fill=NAVY, sw=0),
          path("M25 28 q5 -3 8 2 q2 5 -3 6 q-6 1 -6 -4 z", fill=NAVY, sw=0)]
    b += [dot(43, 15, 1.1), dot(47, 22, 1.1), dot(42, 29, 1.1), dot(46, 34, 1.1)]
    b += [arrow(15, 24, 22, 24, SWT)]
    return svg("".join(b), "UF", "OP-UF — Ultrafiltration: colloids blocked, salts pass.")


def op_fo():
    b = [stub(2, 15, 11), stub(2, 33, 11), stub(53, 15, 62), stub(53, 33, 62),
         vessel("membrane")]
    b += [rect(31, 8, 2.5, 32, 0, fill=FAMILY["membrane"][0], sw=SWT)]
    # osmosis: water crosses on its own (curved arrow), no pressure
    b += [path("M20 30 q12 -12 24 -4", sw=SW), arrow(41, 25.6, 45.4, 27.2, SW)]
    b += [dot(45, 16, 2.2), dot(50, 20, 2.2), dot(43, 22, 2.2)]  # strong draw side
    b += [dot(18, 19, 1.1)]
    return svg("".join(b), "FO", "OP-FO — Forward Osmosis: draw solution pulls water across.")


def op_pro():
    b = [stub(2, 18, 11), stub(2, 34, 11), stub(53, 34, 62), vessel("membrane", y=12, h=28, rx=6)]
    b += [rect(31, 12, 2.5, 28, 0, fill=FAMILY["membrane"][0], sw=SWT)]
    b += [path("M20 32 q12 -10 22 -3", sw=SWT)]
    # turbine = the power take-off, PRO's signature
    b += [circle(45, 12, 8, fill=WHITE), line(45, 5, 45, 19, SWT), line(39, 8.5, 51, 15.5, SWT),
          line(39, 15.5, 51, 8.5, SWT), circle(45, 12, 2, fill=NAVY, sw=0)]
    b += [arrow(52, 6, 56, 9, SWT)]
    return svg("".join(b), "PRO", "OP-PRO — Pressure-Retarded Osmosis: osmotic power via turbine.")


def op_med():
    acc = FAMILY["thermal"][0]
    b = [stub(2, 30, 12), stub(52, 30, 62)]
    # three effects in series — MED's signature repetition
    for i, x in enumerate((12, 26, 40)):
        b += [rect(x, 16, 12, 24, 2, fill=FAMILY["thermal"][1])]
        b += [arrow(x + 6, 15, x + 6, 7, SWT, 2.6, acc)]   # vapour to the next effect
        b += [path(f"M{x + 3} 34 q3 -3 6 0", sw=SWT)]
    return svg("".join(b), "MED", "OP-MED — Multi-Effect Distillation: vapour reused effect to effect.")


def op_msf():
    acc = FAMILY["thermal"][0]
    b = [stub(2, 14, 10), stub(54, 38, 62)]
    # descending flash stages — a staircase, unmistakable vs MED
    b += [path("M10 12 h14 v8 h14 v8 h14 v12 h-42 z", fill=FAMILY["thermal"][1])]
    for x, y in ((17, 12), (31, 20), (45, 28)):
        b += [arrow(x, y - 1, x, y - 8, SWT, 2.6, acc)]
    b += [path("M12 38 h40", sw=SWT)]
    return svg("".join(b), "MSF", "OP-MSF — Multi-Stage Flash: brine flashes down a stage cascade.")


def op_mvc():
    acc = FAMILY["thermal"][0]
    b = [stub(2, 32, 12), stub(52, 32, 62)]
    b += [rect(12, 20, 40, 20, 4, fill=FAMILY["thermal"][1])]
    # mechanical compressor on the vapour loop — MVC's signature
    b += [circle(32, 10, 8, fill=WHITE), path("M28 14 l8 -8 M28 6 l8 8", sw=SWT)]
    b += [path("M18 20 q0 -10 6 -10", sw=SWT, cap="round"),
          arrow(40, 10, 46, 10, SWT), path("M46 10 q6 0 6 10", sw=SWT)]
    b += [path("M18 30 q3 -3 6 0 q3 3 6 0", sw=SWT, cap="round")]
    return svg("".join(b), "MVC", "OP-MVC — Mechanical Vapour Compression: compressor drives evaporation.")


def op_md():
    acc = FAMILY["thermal"][0]
    b = [stub(2, 14, 11), stub(2, 34, 11), stub(53, 14, 62), stub(53, 34, 62),
         vessel("thermal")]
    # POROUS membrane (dashed) — vapour crosses, liquid does not
    b += [line(32, 9, 32, 39, 2.6, acc, dash="3 3")]
    # hot side: heat waves;  cold side: condensate droplets
    b += [path("M16 14 q3 -4 6 0 q3 4 6 0", sw=SWT),
          path("M16 22 q3 -4 6 0 q3 4 6 0", sw=SWT)]
    b += [path("M40 18 q3 5 0 6 q-4 -1 0 -6 z", fill=acc, sw=SWT),
          path("M46 26 q3 5 0 6 q-4 -1 0 -6 z", fill=acc, sw=SWT)]
    return svg("".join(b), "MD", "OP-MD — Membrane Distillation: vapour crosses a porous membrane.")


def op_evappond():
    acc = FAMILY["thermal"][0]
    b = [stub(2, 30, 12), stub(52, 36, 62)]
    # sun + open pond cross-section — nothing else looks like this
    b += [circle(13, 10, 5, fill=acc, sw=SWT)]
    for dx, dy in ((0, -8.5), (6, -6), (8.5, 0), (-8.5, 0), (-6, -6)):
        b += [line(13 + dx * 0.72, 10 + dy * 0.72, 13 + dx, 10 + dy, SWT)]
    b += [path("M12 26 h40 l-6 16 h-28 z", fill=FAMILY["thermal"][1])]
    b += [line(14, 26, 50, 26, SWT)]
    for x in (26, 34, 42):
        b += [arrow(x, 24, x, 16, SWT, 2.6, acc)]
    b += [dot(24, 36, 1.6), dot(32, 38, 1.6), dot(40, 36, 1.6)]  # salt left behind
    return svg("".join(b), "EVAP", "OP-EVAPPOND — Solar Evaporation Pond: sun-driven brine concentration.")


def op_ed():
    acc = FAMILY["electro"][0]
    b = [stub(2, 14, 13), stub(2, 34, 13), stub(51, 14, 62), stub(51, 34, 62),
         stack("electro")]
    # electrode plates + alternating ion-exchange membranes
    b += [rect(13, 8, 5, 32, 0, fill=acc, sw=SWT), rect(46, 8, 5, 32, 0, fill=acc, sw=SWT)]
    for x in (25, 32, 39):
        b += [line(x, 10, x, 38, SWT)]
    b += [path("M13.5 20 h4 M15.5 18 v4", sw=SWT, stroke=WHITE)]      # +
    b += [path("M46.5 20 h4", sw=SWT, stroke=WHITE)]                   # −
    b += [dot(28.5, 17, 1.5), dot(35.5, 24, 1.5), dot(28.5, 31, 1.5)]
    return svg("".join(b), "ED", "OP-ED — Electrodialysis: ions driven through membrane pairs.")


def op_edi():
    acc = FAMILY["electro"][0]
    b = [stub(2, 14, 13), stub(2, 34, 13), stub(51, 14, 62), stub(51, 34, 62),
         stack("electro")]
    b += [rect(13, 8, 5, 32, 0, fill=acc, sw=SWT), rect(46, 8, 5, 32, 0, fill=acc, sw=SWT)]
    b += [line(24, 10, 24, 38, SWT), line(40, 10, 40, 38, SWT)]
    # the resin fill between the membranes is what makes it EDI, not ED
    for cx in (28, 33, 37):
        for cy in (14, 21, 28, 35):
            b += [circle(cx + (2 if cy in (21, 35) else 0), cy, 1.9, fill=WHITE, sw=1.1)]
    b += [path("M13.5 20 h4 M15.5 18 v4", sw=SWT, stroke=WHITE)]
    b += [path("M46.5 20 h4", sw=SWT, stroke=WHITE)]
    return svg("".join(b), "EDI", "OP-EDI — Electrodeionization: resin-filled cells polish to ultrapure.")


def op_cdi():
    acc = FAMILY["electro"][0]
    b = [stub(2, 24, 12), stub(52, 24, 62)]
    b += [rect(12, 10, 40, 28, 3, fill=FAMILY["electro"][1])]
    # two thick porous electrodes storing ions on their surface — capacitor idea
    b += [rect(17, 14, 8, 20, 1.5, fill=acc, sw=SWT), rect(39, 14, 8, 20, 1.5, fill=acc, sw=SWT)]
    for cy in (18, 24, 30):
        b += [dot(27, cy, 1.4), dot(37, cy, 1.4)]
    b += [path("M21 8 v-5 M43 8 v-5 M15 3 h12 M37 3 h12", sw=SWT)]  # capacitor leads
    return svg("".join(b), "CDI", "OP-CDI — Capacitive Deionization: ions stored on charged electrodes.")


def op_chloralk():
    acc = FAMILY["electro"][0]
    b = [stub(2, 30, 13), stub(51, 30, 62)]
    b += [rect(13, 12, 38, 30, 3, fill=FAMILY["electro"][1])]
    b += [line(32, 12, 32, 42, 2.4, acc)]
    # gas bubbles rising on BOTH sides + two gas take-offs — the chlor-alkali picture
    for cx, cy in ((20, 30), (24, 24), (19, 20), (23, 16), (40, 30), (44, 24), (39, 20), (43, 16)):
        b += [circle(cx, cy, 2, fill=WHITE, sw=1.2)]
    b += [arrow(20, 12, 20, 4, SWT, 2.6, acc), arrow(44, 12, 44, 4, SWT, 2.6, acc)]
    return svg("".join(b), "CHLOR", "OP-CHLORALK — Chlor-Alkali cell: Cl2 and H2 evolve either side.")


def op_ix():
    acc = FAMILY["electro"][0]
    b = [vstub(32, 2, 6), stub(2, 24, 20), stub(44, 24, 62)]
    b += [column("electro")]
    # regular resin beads + captured hardness ions (dark) — a packed ION-EXCHANGE bed
    for row, cy in enumerate((13, 20, 27, 34)):
        for i, cx in enumerate((25, 32, 39)):
            off = 3.5 if row % 2 else 0
            if cx + off <= 41:
                b += [circle(cx + off, cy, 2.6, fill=WHITE, sw=1.2)]
    b += [dot(25, 13, 1.3), dot(35.5, 20, 1.3), dot(39, 27, 1.3)]
    return svg("".join(b), "IX", "OP-IX — Ion Exchange: hardness captured on a resin bed.")


def op_dle():
    acc = FAMILY["sorption"][0]
    b = [vstub(32, 2, 6), stub(2, 24, 20), stub(44, 24, 62)]
    b += [column("sorption")]
    # sorbent beads; the ones that grabbed Li are filled with the family accent + "Li"
    beads = ((26, 13), (38, 14), (26, 21), (38, 22), (26, 29), (38, 30), (26, 37), (38, 38))
    for i, (cx, cy) in enumerate(beads):
        got_li = i in (1, 2, 5)
        b += [circle(cx, cy, 2.6, fill=acc if got_li else WHITE, sw=1.2)]
    b += [f'<text x="32" y="26" text-anchor="middle" fill="{NAVY}" '
          f'font-family="Segoe UI, Arial" font-size="8" font-weight="700">Li</text>']
    b += [arrow(32, 42, 32, 46, SWT)]
    return svg("".join(b), "DLE", "OP-DLE — Direct Lithium Extraction: selective Li uptake on sorbent.")


def op_sx():
    acc = FAMILY["sorption"][0]
    b = [stub(2, 12, 10), stub(2, 34, 10), stub(54, 14, 62), stub(54, 34, 62)]
    # MIXER (round tank, agitator) + SETTLER (tank with a phase line) — a two-vessel
    # silhouette nothing else in the pack has
    b += [rect(9, 10, 18, 30, 8, fill=FAMILY["sorption"][1])]
    b += [line(18, 10, 18, 3, SW), path("M13 22 h10 M15 27 h6", sw=SWT)]   # shaft + blades
    b += [rect(33, 12, 21, 26, 3, fill=WHITE)]
    b += [line(33, 25, 54, 25, 2.6, acc)]                                   # phase interface
    b += [dot(39, 18, 1.6), dot(47, 20, 1.6), dot(43, 31, 1.6), dot(49, 32, 1.6)]
    b += [arrow(27, 20, 33, 20, SWT), arrow(33, 30, 27, 30, SWT)]           # counter-current
    return svg("".join(b), "SX", "OP-SX — Solvent Extraction: mixer plus settler, counter-current.")


def op_cryst():
    b = [stub(2, 14, 14), stub(50, 14, 62), vstub(32, 46, 50)]
    # cone-bottomed crystallizer body (crystals leave the bottom nozzle)
    b += [path("M14 9 h36 v15 l-18 20 -18 -20 z", fill=FAMILY["sorption"][1])]
    for cx, cy, s in ((25, 20, 3.6), (37, 18, 3.0), (31, 27, 3.8), (39, 26, 2.6), (30, 15, 2.4)):
        b += [path(f"M{cx} {cy - s} L{cx + s} {cy} L{cx} {cy + s} L{cx - s} {cy} z",
                   fill=WHITE, sw=1.3)]
    return svg("".join(b), "CRYST", "OP-CRYST — Crystallizer: solubility-limited crystal yield.")


def op_ppt():
    acc = FAMILY["sorption"][0]
    b = [stub(2, 16, 12), stub(52, 16, 62), stub(32, 50, 32)]
    b += [rect(12, 10, 40, 20, 2, fill=FAMILY["sorption"][1])]
    # reagent dosed in from the top + floc settling into a sludge cone
    b += [vstub(32, 2, 6), arrow(32, 6, 32, 10, SWT, 3.0, acc)]
    b += [path("M12 30 h40 l-14 14 h-12 z", fill=WHITE)]
    for cx, cy in ((26, 34), (33, 33), (30, 39), (37, 37)):
        b += [circle(cx, cy, 2.1, fill=acc, sw=1.2)]
    b += [dot(20, 20, 1.5), dot(27, 17, 1.5), dot(43, 21, 1.5)]
    b += [vstub(32, 44, 50)]
    return svg("".join(b), "PPT", "OP-PPT — Chemical Precipitation: reagent dosing, wet sludge out.")


def op_gac():
    acc = FAMILY["sorption"][0]
    b = [vstub(32, 2, 6), stub(2, 24, 20), stub(44, 24, 62), vstub(32, 42, 46)]
    b += [column("sorption")]
    # ANGULAR carbon granules (vs the round resin beads of IX/DLE) + adsorbed dots
    grains = ((25, 12), (33, 15), (38, 11), (27, 20), (35, 23), (24, 28),
              (33, 31), (39, 27), (28, 36), (36, 38))
    for cx, cy in grains:
        b += [path(f"M{cx - 2.6} {cy} L{cx - 0.6} {cy - 2.6} L{cx + 2.4} {cy - 1.4} "
                   f"L{cx + 1.8} {cy + 2.2} L{cx - 1.6} {cy + 2.4} z", fill=NAVY, sw=0)]
    b += [dot(30, 17, 1.1, acc), dot(37, 34, 1.1, acc), dot(26, 32, 1.1, acc)]
    b += [arrow(32, 6, 32, 10, SWT), arrow(32, 38, 32, 42, SWT)]
    return svg("".join(b), "GAC", "OP-GAC — Activated Carbon: adsorption on a granular carbon bed.")


def _electrolyzer(label, comment, bubbles):
    """Shared PEM/AEL body: a cell stack splitting water into H2 + O2."""
    acc = FAMILY["energy"][0]
    b = [stub(2, 32, 13), stack("energy", y=10, h=30)]
    for x in (21, 28, 35, 42):
        b += [line(x, 12, x, 38, SWT)]
    b += [rect(13, 10, 5, 30, 0, fill=acc, sw=SWT), rect(46, 10, 5, 30, 0, fill=acc, sw=SWT)]
    b += [arrow(20, 10, 20, 2, SWT, 3.0, acc), arrow(44, 10, 44, 2, SWT, 3.0, acc)]
    if bubbles:
        for cx, cy in ((25, 20), (31, 26), (38, 18), (33, 33), (25, 31)):
            b += [circle(cx, cy, 2, fill=WHITE, sw=1.2)]
    else:
        b += [line(32, 12, 32, 38, 2.6, acc)]   # solid polymer membrane
    return svg("".join(b), label, comment)


def op_pem():
    return _electrolyzer("PEM", "OP-PEM — PEM Electrolyzer: solid-membrane water splitting.", False)


def op_ael():
    return _electrolyzer("AEL", "OP-AEL — Alkaline Electrolyzer: liquid KOH cells, gas bubbles.", True)


def op_fc():
    acc = FAMILY["energy"][0]
    b = [stub(2, 16, 13), stub(2, 32, 13), stub(51, 32, 62), stack("energy", y=10, h=30)]
    for x in (22, 30, 38):
        b += [line(x, 12, x, 38, SWT)]
    b += [rect(13, 10, 5, 30, 0, fill=acc, sw=SWT), rect(46, 10, 5, 30, 0, fill=acc, sw=SWT)]
    # power out — the lightning bolt separates FC from the electrolyzers
    b += [path("M34 2 L26 14 h6 l-3 10 10 -13 h-6 z", fill=acc, sw=SWT)]
    return svg("".join(b), "FC", "OP-FC — PEM Fuel Cell: H2 and air in, electric power out.")


def op_rpb():
    acc = FAMILY["energy"][0]
    b = [stub(2, 24, 12), stub(52, 24, 62), vstub(32, 2, 6)]
    # a spinning rotor — the only circular block in the pack
    b += [circle(32, 24, 20, fill=FAMILY["energy"][1])]
    b += [circle(32, 24, 7, fill=WHITE)]
    import math
    for k in range(8):
        a0 = k * math.pi / 4
        b += [line(32 + 7.5 * math.cos(a0), 24 + 7.5 * math.sin(a0),
                   32 + 18 * math.cos(a0), 24 + 18 * math.sin(a0), SWT)]
    b += [path("M44 9 a20 20 0 0 1 6 9", sw=SW), arrow(49.4, 15.5, 50.6, 19.5, SWT)]
    return svg("".join(b), "RPB", "OP-RPB — Rotating Packed Bed: HiGee rotor intensifies absorption.")


def op_uvaop():
    acc = FAMILY["energy"][0]
    b = [stub(2, 24, 11), stub(53, 24, 62)]
    b += [rect(11, 10, 42, 28, 4, fill=FAMILY["energy"][1])]
    # UV lamp radiating — unmistakable
    b += [rect(29, 16, 6, 16, 3, fill=acc, sw=SWT)]
    import math
    for k in range(8):
        a0 = k * math.pi / 4 + math.pi / 8
        b += [line(32 + 7 * math.cos(a0), 24 + 7 * math.sin(a0),
                   32 + 12.5 * math.cos(a0), 24 + 12.5 * math.sin(a0), SWT, acc)]
    b += [dot(17, 18, 1.4), dot(20, 30, 1.4), dot(46, 20, 1.4), dot(44, 31, 1.4)]
    return svg("".join(b), "UVAOP", "OP-UVAOP — UV / Advanced Oxidation: lamp dose destroys micropollutants.")


def op_mixer_demo():
    acc = FAMILY["membrane"][0]
    b = [stub(2, 16, 14), stub(2, 32, 14), stub(50, 24, 62)]
    b += [path("M14 10 h10 l16 10 v8 l-16 10 h-10 z", fill=FAMILY["membrane"][1])]
    b += [dot(22, 20, 1.6), dot(28, 26, 1.6), dot(22, 31, 1.6)]
    return svg("".join(b), "MIX", "OP-MIXER-DEMO — framework demo mixer.")


BLOCKS = {
    "OP-RO": op_ro, "OP-NF": op_nf, "OP-UF": op_uf, "OP-FO": op_fo, "OP-PRO": op_pro,
    "OP-MED": op_med, "OP-MSF": op_msf, "OP-MVC": op_mvc, "OP-MD": op_md,
    "OP-EVAPPOND": op_evappond,
    "OP-ED": op_ed, "OP-EDI": op_edi, "OP-CDI": op_cdi, "OP-CHLORALK": op_chloralk,
    "OP-IX": op_ix,
    "OP-DLE": op_dle, "OP-SX": op_sx, "OP-CRYST": op_cryst, "OP-PPT": op_ppt, "OP-GAC": op_gac,
    "OP-PEM": op_pem, "OP-AEL": op_ael, "OP-FC": op_fc, "OP-RPB": op_rpb, "OP-UVAOP": op_uvaop,
    "OP-MIXER-DEMO": op_mixer_demo,
}


if __name__ == "__main__":
    for code, fn in sorted(BLOCKS.items()):
        p = os.path.join(OUT, code + ".svg")
        with open(p, "w", encoding="utf-8") as f:
            f.write(fn())
        print("wrote", os.path.basename(p))
    print(len(BLOCKS), "icons generated")
