using System;
using System.Globalization;
using System.IO;
using OPBlocks.Core;

namespace OproValidation
{
    /// <summary>
    /// Emits a human-readable reference table for the OP-RO canonical cases by
    /// calling the shared <see cref="RoModel"/> engine — the same code the
    /// CAPE-OPEN block runs. This is a DOCUMENTATION artifact (cases.txt); the
    /// authoritative approval gate lives in
    /// tests/UnitTests/RoCapeOpenValidationTests.cs, which replays every case
    /// through the real block and adds independent physical-range checks.
    /// </summary>
    internal static class Program
    {
        private const double MwWater = 18.0153, MwNaCl = 58.442467, MwMgCl2 = 95.211;

        private sealed class Case
        {
            public string Name;
            public RoModel.Mode Mode = RoModel.Mode.Rating;
            public RoModel.Erd Erd = RoModel.Erd.None;
            public double Area = 40, PermA = 1.0, Rej = 99.5, Applied = 60, VantHoff = 2.0,
                          PumpEff = 80, MaxRec = 50, TargetRec = 45, DesignFlux = 15, ErdEff = 96;
            public double[] Feed; public double[] Mw; public int Wi; public double Tk = 298.15;
        }

        private static int Main(string[] args)
        {
            double[] sw = { 23.5, 0.263 };
            var cases = new[]
            {
                new Case { Name = "seawater-rating", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0 },
                new Case { Name = "seawater-rating-PX", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Erd = RoModel.Erd.PressureExchanger, ErdEff = 96 },
                new Case { Name = "seawater-rating-turbine", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Erd = RoModel.Erd.Turbine, ErdEff = 80 },
                new Case { Name = "design-45pct", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Mode = RoModel.Mode.Design },
                new Case { Name = "design-45pct-PX", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Mode = RoModel.Mode.Design, Erd = RoModel.Erd.PressureExchanger },
                new Case { Name = "brackish-high-recovery", Feed = new[]{55.0,0.11}, Mw = new[]{MwWater,MwNaCl}, Wi = 0, PermA = 6, Applied = 20, MaxRec = 85, TargetRec = 80 },
                new Case { Name = "oversized-area-capped", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Area = 400, PermA = 5, Applied = 70 },
                new Case { Name = "no-permeation", Feed = sw, Mw = new[]{MwWater,MwNaCl}, Wi = 0, Applied = 20 },
                new Case { Name = "multisalt", Feed = new[]{23.5,0.20,0.06}, Mw = new[]{MwWater,MwNaCl,MwMgCl2}, Wi = 0 },
            };

            var ci = CultureInfo.InvariantCulture;
            string outPath = args.Length > 0 ? args[0] : "cases.txt";
            using (var w = new StreamWriter(outPath))
            {
                w.WriteLine("OP-RO canonical reference cases — generated by RoModel (the block's own engine).");
                w.WriteLine("Volumes use rho = 1000 kg/m3 (package-independent reference).");
                w.WriteLine(new string('=', 100));
                foreach (var c in cases)
                {
                    var spec = new RoModel.Spec
                    {
                        CalcMode = c.Mode, ErdType = c.Erd, AreaM2 = c.Area, WaterPermA = c.PermA,
                        SaltRejPct = c.Rej, AppliedBar = c.Applied, VantHoffI = c.VantHoff, PumpEffPct = c.PumpEff,
                        MaxRecoveryPct = c.MaxRec, TargetRecoveryPct = c.TargetRec, DesignFluxLMH = c.DesignFlux, ErdEffPct = c.ErdEff,
                    };
                    double piFeed = ProcessOps.OsmoticPressureBar(null, c.Feed, c.Wi, c.VantHoff, c.Tk, null);
                    RoModel.Split s = RoModel.Solve(spec, c.Feed, c.Wi, c.Mw, c.Tk, piFeed);
                    double feedM3s = Mass(c.Feed, c.Mw) / 1000.0;
                    double permM3s = ProcessOps.Sum(s.PermMol) > 1e-30 ? Mass(s.PermMol, c.Mw) / 1000.0 : 0.0;
                    double concM3s = ProcessOps.Sum(s.ConcMol) > 1e-30 ? Mass(s.ConcMol, c.Mw) / 1000.0 : 0.0;
                    RoModel.Energy e = RoModel.CalcEnergy(spec, s.AppliedBarUsed, feedM3s, permM3s, concM3s);

                    w.WriteLine();
                    w.WriteLine("[{0}]  mode={1}  ERD={2}", c.Name, c.Mode, c.Erd);
                    w.WriteLine(string.Format(ci,
                        "  recovery={0:0.###}%  flux={1:0.##} LMH  piFeed={2:0.##}  piAvg={3:0.##}  NDP={4:0.##} bar",
                        s.Recovery * 100, s.FluxLMH, s.PiFeedBar, s.PiAvgBar, s.NdpBar));
                    w.WriteLine(string.Format(ci,
                        "  permTDS={0:0.#} ppm  concTDS={1:0.#} ppm  rejObs={2:0.###}%  capped={3}",
                        s.TdsPermPpm, s.TdsConcPpm, s.SaltRejObsPct, s.RecoveryCapped));
                    w.WriteLine(string.Format(ci,
                        "  grossPump={0:0.###} kW  grossSEC={1:0.###}  ERDrec={2:0.###} kW  netPump={3:0.###} kW  netSEC={4:0.###}  saving={5:0.#}%",
                        e.GrossPumpKW, e.SecGross, e.ErdRecoveredKW, e.NetPumpKW, e.SecNet, e.EnergySavingPct));
                    if (c.Mode == RoModel.Mode.Design)
                        w.WriteLine(string.Format(ci, "  requiredArea={0:0.##} m2  requiredPressure={1:0.##} bar",
                            s.RequiredAreaM2, s.RequiredPressureBar));
                }
            }
            Console.WriteLine("wrote " + outPath + " (" + cases.Length + " cases)");
            return 0;
        }

        private static double Mass(double[] mol, double[] mw)
        {
            double kg = 0;
            for (int i = 0; i < mol.Length; i++) kg += mol[i] * mw[i] / 1000.0;
            return kg;
        }
    }
}
